services:

  postgres:
    image: postgres:17
    container_name: quant-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: quant_platform
      POSTGRES_USER: quant_user
      POSTGRES_PASSWORD: quant_password

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
